[workspace]

members = [
    "bookworm-tui",
    "bookworm-app",
    "bookworm-records",
    "bookworm-database",
    "bookworm-input",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'

[profile.dev]
opt-level = 2
