[workspace]

members = [
    "bookstore-tui",
    "bookstore-app",
    "bookstore-records",
    "bookstore-database",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'

[profile.dev]
opt-level = 2
